# Generated by Django 5.0 on 2023-12-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=80)),
                ('sets', models.IntegerField(blank=True, default=3)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
